### ISSUE TITLE
sorting options

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/athene#14]
would it be possible to sort seekers alphabetically on the main list?

**Comment by j00bar** [comment]
Seekers are already alphabetically ordered by last name. You can select other columns to order by clicking on the header above them. Please let me know if this addresses your concern.

**Comment by howtohumanbetter** [comment]
ohhh I see. Sorting by first name would be helpful, if possible.

**Comment by j00bar** [comment]
Fixed somewhere.
